#! /bin/bash

# requirements: go install -v github.com/charmbracelet/gum@latest

do_push() {
  git add .
  git commit -m "$1"
  git push
}

COMMIT_MSG=$(gum write --placeholder "commit message...")

gum confirm "commit changes??" && do_push $COMMIT_MSG
